permitColumns = [
    "PM #",
    "Mat Code",
    "Sub-Category",
    "Open Dependencies",
    "Div",
    "Work Plan Date",
    "CLICK Start Date",
    "CLICK End Date",
    "LEAPS Prescreening Cycle Time Days",
    "Days in PEND",
    "SP56 User Status",
    "RP56 User Status",
    "E Permit Status",
    "Permit Application Date",
    "Encroachment Permit Expiration Date",
    "Permit Expiration Date",
    "Action",
]

permitColumns_combinedRequestForExtensionAndSubmittedOver = [
    "PM #",
    "Mat Code",
    "Sub-Category",
    "Open Dependencies",
    "Div",
    "Work Plan Date",
    "CLICK Start Date",
    "CLICK End Date",
    "LEAPS Prescreening Cycle Time Days",
    "Days in PEND",
    "SP56 User Status",
    "RP56 User Status",
    "E Permit Status",
    "Permit Application Date",
    "Encroachment Permit Expiration Date",
    "Permit Expiration Date",
    "LEAPS Expected EOD",
    "Action",
]